### ISSUE TITLE
Error with install: autoreconf fails to run aclocal

### ISSUE THREAD

**Issue by Enviy** [buffer/pylibemu#24]
This is on macOS High Sierra (10.13.6). The initial issue was an install error with "pip install thug" the error was for the pylibemu dependency. I wasn't sure if there was a better place to report this error or seek assistance. Can someone please advise on how I might be able to fix this error? Thanks in advance!

Steps taken:
sudo git clone --recursive https://github.com/buffer/pylibemu.git
sudo python setup.py install

Output (Error):
> running install
running build
running build_clib
running 'autoreconf -v -i -f' for library 'emu'
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 244, in <module>
    libraries    = ["emu"]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
    self.run_command('build')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 88, in finalize_options
    check_call(['autoreconf', '-v', '-i', '-f'], cwd = build_info['local_source'], env = env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['autoreconf', '-v', '-i', '-f']' returned non-zero exit status 1

**Comment by buffer** [comment]
Sorry for the late reply. I totally missed the issue. Apparently you're missing aclocal. aclocal is part of GNU's automake set of tools. You should be able to simply run 'brew install automake' to add it to your path. Let me know if that solves your issue

**Comment by wesinator** [comment]
Had a similar issue on Ubuntu - running `apt install autoconf libtool` seemed to fix it.

**Comment by ericyoungberg** [comment]
For me, I had to install `automake` instead of `autoconf` on Ubuntu 18.04.

**Comment by lijiaocn** [comment]
install automake, for centos, command is : yum install -y automake

**Comment by Enviy** [comment]
I apologize for the crazy delayed response. The error ended up being that I was really trying to get it to run on Python 3.7. There are a few dependencies which aren't supported on more recent versions of Python.

**Comment by jakesyl** [comment]
automake worked for me

**Comment by sirnicolas21** [comment]
(raspberry)
sudo apt install automake

**Comment by jrihak** [comment]
Fedora 31 + Python 3.7.6:
`sudo dnf install automake libtool`

**Comment by ishanPy** [comment]
Automake for Arch Linux works !
`sudo pacman -S libtool automake`
Have a good day :+1:

**Comment by evandorn** [comment]
If anyone runs into this in 2023 on an M1 mac install automake via brew install also fixed it for me

**Comment by kaigama2** [comment]
"brew install automake"...... it works for me bro 🤓🤓🙌

**Comment by bootstrap314** [comment]
It would be nice if the bundled docker-cli was seperated from the engine component (or provide instructions on how to connect an alternative CLI).

While an alias will suffice, there are features available within Podman that are not within Docker (cli) that can be jarring for users used to Podman.

I use Podman with crun to run WASM containers, and I would like to be able to use consistent tooling across my environments.
